apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: fluxcd-demo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: snoppy
  targetNamespace: fluxcd-demo
  chart:
    git: git@github.com:ElianaArjona/snoppy-dog.git
    path: helm-charts/snoppy
    ref: helm-flux
